### PR TITLE
Add implementation of fmt::Display for SqlQuery

### PR DESCRIPTION
**Pull request by ivanceras**
This change is [Reviewable](https://reviewable.io/reviews/ms705/nom-sql/10)

### CODE REVIEW

**Comment by ivanceras** [comment]
PR for issue https://github.com/ms705/nom-sql/issues/4

**Comment by ms705** [comment]
Sorry for leaving this dangling! I'm currently travelling, but should get around to reviewing and merging this at the end of the week.

**Comment by ms705** [comment]
This looks good to me! Some minor conflicts with `master` need resolving, and we need to add support for the new `CompoundSelect` variant of the `SqlQuery` enum, but otherwise this is ready to merge.

**Comment by ms705** [comment]
Merged, thanks! @ivanceras

**Pull request merged**
