### PR TITLE
Upgrade nom

### PR DESCRIPTION
**Pull request by ekmartin**
This upgrades `nom` to the latest stable version, 3.2.1. The changes can mostly be grouped into a few categories:

* `chain!` -> `do_parse!`
Slightly different syntax, and doesn't take a closure as its final argument anymore.
* `caseless_tag` -> builtin `tag_no_case`
* `multispace?` -> `opt!(multispace)` and similar

## TODOs:
- [x] Fix `statement_terminator`. `eof` was replaced by an `eof!()` macro, but they seem to behave differently. I've tried making `statement_terminator` work with both semicolons, line endings and end of input, however I haven't gotten the last one [working yet](https://github.com/ms705/nom-sql/compare/master...ekmartin:nom-upgrade?expand=1#diff-7a0baccb3a5e33521fb7234c60ab554e).

- [x] ~Upgrade to nom 4. It's currently at alpha 2, so it looks like a release might be right around the corner. I've gotten nom-sql to compile [here](https://github.com/ekmartin/nom-sql/commit/1868a8b4465e400d87009a3e412850523f2ea053) but it has a few test failures that look similar to the `statement_terminator` issues.~ **EDIT:** Might be better to try to get this merged first and wait with nom 4 until it's released.

## Upgrade references
* Upgrading to nom 2: https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_2.md
* Upgrading to nom 3 (changelog): https://github.com/Geal/nom/blob/master/CHANGELOG.md#300---2017-05-12
* Upgrading to nom 4: https://github.com/Geal/nom/blob/3ccab582a168bfa251303e21cb93fb31740b76fc/doc/upgrading_to_nom_4.md

There's probably quite a few subtle differences we'll have to investigate further as well.

### CODE REVIEW

**Comment by ms705** [comment]
Great work -- apologies for the delay. I'll get back to this after the SIGCOMM deadline tonight.

**Comment by ekmartin** [comment]
No worries, no rush at all. I took a second look at the `statement_terminator` issue, and it seems to be fixed by replacing usages of `opt!(multispace)` with `opt!(complete!(multispace))` - so I added a helper for that. 

If I'm understanding it correctly, it seems like nom 2 [changed some parsers](https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_2.md#parsers-returning-incomplete-instead-of-an-error-on-empty-input) into returning `Incomplete` instead of an error for empty inputs, which means empty inputs won't work with `opt!(multispace)`. There's some more info about it here: https://github.com/Geal/nom/issues/271. Looking at the work-in-progress [changelog entries](https://github.com/Geal/nom/blob/master/CHANGELOG.md) for nom 4 it looks there's more `Incomplete` related changes further ahead as well.

Also ran distributary against this branch, which passed all the tests at least.

**Comment by ms705** [comment]
Apologies, I'll actually get to dealing with this tomorrow!

`statement_terminator` has always been problematic and the semantics of `eof` in nom have always been a bit funky; I'm not surprised it keeps causing trouble.

Parsers returning `Incomplete` are actually a bit painful for us to deal with, because nom (at least in older versions) doesn't backtrack when a child parser returns `Incomplete`; hence the liberally sprinkled `complete!` around any `chain!` in the old code. Looks like we need that in even more places now!

**Comment by ivanceras** [comment]
Speaking of shortcomings of nom, I came across of [pom](https://github.com/J-F-Liu/pom) which feels way more intuitive and concise than nom. I've been playing with it a little bit, and I'm planning to make a derivative of this project using pom and with support for postgrsql as well, since I'm mostly working with postgresql database. I would just call is `pom-sql`(surprise). Who's with me?

**Comment by ms705** [comment]
Let's merge this (finally)!

@ekmartin -- I assume we actually need `verbose-errors`? From the description in the upgrade guide, it seems like we shouldn't, since we don't currently propagate errors back (though we should -- it would make parse errors much easier to debug!). However, I assume you added it for a reason.

@ivanceras pom looks intriguing! Feel free to take a stab at porting this project; I personally unfortunately won't have cycles to work on a port for a while (`nom-sql` grew out of need for a different project, and it's "good enough" for now). Postgres compatibility would be neat -- `nom-sql`'s current compatibility story is "bits of SQLite and bits of MySQL, as needed by our queries" ;-)

**Pull request merged**
